### ISSUE TITLE
Interceptors

### ISSUE THREAD

**Issue by jamesholcomb** [humana-fragilitas/ES6-Rest-Client#2]
https://gist.github.com/bryanrsmith/e8189b6b704fbd5ef21b

What do you think about implementing something similar in rest-client?

**Comment by humana-fragilitas** [comment]
I believe that the ES6 Rest Client library should strictly adhere to the separation of concerns design principle: its only purpose is to provide a semantic, intuitive interface suitable for communication with HTTP-based RESTful APIs, whereas the sample gist you are referring to seems to be targeting at least a couple more problems: chaining and conditional handling.

Ideally, in my opinion, handlers (or interceptors, if you prefer) meant to conditionally divert the application flow should live in their own domain, outside the client; furthermore, cascading sequences of promises can also efficiently be flattened via ES6 generators and ES7 async functions.

A thorough explanation of such use cases, complete with examples, will follow with the next pre-release.

**Comment by jamesholcomb** [comment]
Thanks, looking forward to seeing the use cases.
